version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: coverage run manage.py test
          name: Test
      # - run:
      #     command: coverage report
      #     name: Coverage report
      - run:
          command: codecov
          name: Codecov.io

workflows:
  main:
    jobs:
      - build-and-test
